import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import SearchImage from "../page-components/SearchImage";
import styles from "../styles/Home.module.css";

interface props {
  editorialPhotos: {
    col1: Array<any>;
    col2: Array<any>;
    col3: Array<any>;
  };
}

const Home: NextPage<props> = ({ editorialPhotos }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pixiside</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold">Hi</h1>
      <SearchImage photos={editorialPhotos} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch(
    `https://api.unsplash.com/photos?order_by=popular&per_page=30&client_id=${process.env.UNSPLASH_API_KEY}`
  );
  const result = await response.json();

  const editorialPhotos = {
    col1: result.slice(0, 10),
    col2: result.slice(10, 20),
    col3: result.slice(20, 30),
  };

  return {
    props: {
      editorialPhotos,
    },
  };
};

export default Home;
